apiVersion: v1
kind: Pod
metadata:
  name: pod-yaml
  #namespace: dev # Creates the pod in the dev namespace
  labels:
    name: pod-yaml
    tier: frontend
spec:
  containers:
    - name: yaml-container
      image: nginx